title:              Simple AI & STATS
email:              tranquocdetctk1821@gmail.com
description:        The place to bring on ideas
author:             tran quoc de
baseurl:            ""
url:                "https://tranquocde.github.io"

# Social Profiles
twitter_username:   
github_username:  tranquocde
facebook_username:  tranquocde2003
instagram_username:  tran_quoc_de
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
